name: Run Jest Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  jest-tests:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20] # Run tests on multiple Node.js versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache npm dependencies

      - name: Install dependencies
        run: npm ci # Faster and more reliable than 'npm install'

      - name: Run Jest Tests with Coverage
        run: npx jest test.spec.ts --coverage --verbose
        env:
          NODE_ENV: test

      - name: Upload Jest Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
            name: jest-coverage-report-node-${{ matrix.node-version }} # Unique per Node.js version
            path: coverage/
            retention-days: 7
            #overwrite: true - if you don't use unique id


      - name: Upload Jest Test Results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: jest-test-results-node-${{ matrix.node-version }}
          path: test-results/
          retention-days: 7
